"""AC#1: the env.vps generated by scripts/vps-onboard.sh ends with a newline,
so a later hand-appended VAR=value (e.g. TEST_COMMANDS) parses as its own
independent variable instead of gluing onto the NTFY_TOPIC=... line and being
silently swallowed into that value (which killed the fast gate on the VPS)."""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

_ONBOARD = Path(__file__).resolve().parents[1] / "scripts" / "vps-onboard.sh"


def test_onboard_encodes_env_with_trailing_newline() -> None:
    # Static guard tying to the real script: diff-cover does not measure shell,
    # so a silent regression to `printf '%s'` (no newline) is otherwise invisible.
    line = next(
        ln
        for ln in _ONBOARD.read_text(encoding="utf-8").splitlines()
        if ln.strip().startswith("ENV_CONTENT_B64=")
    )
    assert r"printf '%s\n'" in line, line


@pytest.mark.skipif(
    shutil.which("bash") is None or shutil.which("base64") is None,
    reason="needs bash + base64",
)
def test_appended_var_parses_independently() -> None:
    # Reproduce the exact encode pipeline from vps-onboard.sh: an ENV_CONTENT
    # whose last line is NTFY_TOPIC=<val> with no trailing newline (a shell
    # here-string / command substitution strips it), encoded via
    # `printf '%s\n' | base64 | tr -d '\n'`, then decoded, a TEST_COMMANDS line
    # hand-appended, sourced, and both variables read back. Against the old
    # `printf '%s'` this fails (TEST_COMMANDS glues onto NTFY_TOPIC and is unset).
    script = r"""
set -euo pipefail
unset TEST_COMMANDS NTFY_TOPIC  # hermetic: ignore any ambient loop env
ENV_CONTENT="MAX_LOOPS=4
NTFY_TOPIC=mytopic"
ENV_B64="$(printf '%s\n' "$ENV_CONTENT" | base64 | tr -d '\n')"
tmp="$(mktemp)"
printf '%s' "$ENV_B64" | base64 -d > "$tmp"
printf 'TEST_COMMANDS="echo hi"\n' >> "$tmp"
set -a; . "$tmp"; set +a
printf 'NTFY=[%s] TEST=[%s]\n' "$NTFY_TOPIC" "$TEST_COMMANDS"
"""
    out = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True, check=True
    )
    assert out.stdout.strip() == "NTFY=[mytopic] TEST=[echo hi]"


def test_reproduces_the_original_glue_bug_without_newline() -> None:
    # Negative control: the OLD `printf '%s'` (no newline) glues the appended
    # line onto NTFY_TOPIC, so TEST_COMMANDS never gets set -> `set -u` errors.
    # This proves the behavioural test above actually discriminates the fix.
    if shutil.which("bash") is None or shutil.which("base64") is None:
        pytest.skip("needs bash + base64")
    script = r"""
set -euo pipefail
unset TEST_COMMANDS NTFY_TOPIC  # hermetic: ignore any ambient loop env
ENV_CONTENT="MAX_LOOPS=4
NTFY_TOPIC=mytopic"
ENV_B64="$(printf '%s' "$ENV_CONTENT" | base64 | tr -d '\n')"
tmp="$(mktemp)"
printf '%s' "$ENV_B64" | base64 -d > "$tmp"
printf 'TEST_COMMANDS="echo hi"\n' >> "$tmp"
set -a; . "$tmp"; set +a
printf 'TEST=[%s]\n' "$TEST_COMMANDS"
"""
    out = subprocess.run(["bash", "-c", script], capture_output=True, text=True)
    assert out.returncode != 0  # TEST_COMMANDS unbound under `set -u`
